# Generated by Django 3.0.4 on 2020-03-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('datenaissance', models.DateTimeField()),
                ('adresse', models.TextField()),
                ('tel', models.IntegerField()),
                ('photo', models.TextField()),
                ('statut', models.CharField(max_length=50)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Promotion')),
            ],
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.DeleteModel(
            name='Eleves',
        ),
        migrations.DeleteModel(
            name='Intervenants',
        ),
        migrations.DeleteModel(
            name='Personnes',
        ),
    ]
